AppBundle\Entity\City:
    type: entity
    table: city
    repositoryClass: AppBundle\EntityRepository\CityRepository
    id:
        id:
            id: true
            type: string
            length: 255
        state:
            associationKey: true
    fields:
        name:
            type: string
            length: 255
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    manyToOne:
        state:
            targetEntity: State
            joinColumn:
                name: state
                referencedColumnName: id
            cascade: ["persist", "merge"]
    lifecycleCallbacks: {  }
    gedmo:
        soft_deleteable:
          field_name: deletedAt
          time_aware: false