AppBundle\Entity\Company:
    type: entity
    table: company
    repositoryClass: AppBundle\EntityRepository\CompanyRepository
    id:
        id:
            id: true
            type: string
            length: 255
    fields:
        externalId:
            type: string
            length: 255
            unique: true
        socialReason:
            type: text
        socialObject:
            type: text
        latitude:
            type: text
        longitude:
            type: text
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
    gedmo:
        soft_deleteable:
          field_name: deletedAt
          time_aware: false