AppBundle\Entity\MapRoutePath:
    type: entity
    table: map_route_path
    repositoryClass: AppBundle\EntityRepository\MapRoutePathRepository
    id:
        id:
            id: true
            type: string
            length: 255
    fields:
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    manyToOne:
        mapRoute:
            targetEntity: MapRoute
            joinColumn:
                name: map_route
                referencedColumnName: id
            cascade: ["persist", "merge"]
        startPoint:
            targetEntity: Company
            joinColumn:
                name: start_point
                referencedColumnName: id
            cascade: ["persist", "merge"]
        endPoint:
            targetEntity: Company
            joinColumn:
                name: end_point
                referencedColumnName: id
            cascade: ["persist", "merge"]
    lifecycleCallbacks: {  }
    gedmo:
        soft_deleteable:
          field_name: deletedAt
          time_aware: false