AppBundle\Entity\RefreshToken:
    type: entity
    table: refresh_token
    id:
        id:
            id: true
            type: string
            length: 255
        user:
            associationKey: true
    fields:
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    manyToOne:
        user:
            targetEntity: Customer
            joinColumn:
                name: customer
                referencedColumnName: id
            inversedBy: refreshTokens
            cascade: ["persist", "merge"]
        client:
            targetEntity: Client
            joinColumn:
                name: client
                referencedColumnName: id
            inversedBy: refreshTokens
            cascade: ["persist", "merge"]
    lifecycleCallbacks: {  }
    gedmo:
        soft_deleteable:
          field_name: deletedAt
          time_aware: false