AppBundle\Entity\SharedStaticList:
    type: entity
    table: shared_static_list
    repositoryClass: AppBundle\EntityRepository\SharedStaticListRepository
    id:
        staticList:
            associationKey: true
        customer:
            associationKey: true
    fields:
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    manyToOne:
        staticList:
            targetEntity: StaticList
            joinColumn:
                name: static_list
                referencedColumnName: id
            cascade: ["persist", "merge"]
        customer:
            targetEntity: Customer
            joinColumn:
                name: customer
                referencedColumnName: id
            cascade: ["persist", "merge"]
    lifecycleCallbacks: {  }
    gedmo:
        soft_deleteable:
          field_name: deletedAt
          time_aware: false