AppBundle\Entity\StyledCompany:
    type: entity
    table: styled_company
    repositoryClass: AppBundle\EntityRepository\StyledCompanyRepository
    id:
        company:
            associationKey: true
        customer:
            associationKey: true
    fields:
        style:
            type: string
            length: 255
            unique: true
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    manyToOne:
        company:
            targetEntity: Company
            joinColumn:
                name: company
                referencedColumnName: id
            cascade: ["persist", "merge"]
        customer:
            targetEntity: Customer
            joinColumn:
                name: customer
                referencedColumnName: id
            cascade: ["persist", "merge"]
    lifecycleCallbacks: {  }
    gedmo:
        soft_deleteable:
          field_name: deletedAt
          time_aware: false