NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

customers:
    resource: "AppBundle\Controller\CustomersController"
    prefix:   api/v1
    type:     rest

companies:
    resource: "AppBundle\Controller\CompaniesController"
    prefix:   api/v1
    type:     rest

devices:
    resource: "AppBundle\Controller\DevicesController"
    prefix:   api/v1
    type:     rest

mapRoute:
    resource: "AppBundle\Controller\MapRoutesController"
    prefix:   api/v1
    type:     rest

finance:
    resource: "AppBundle\Controller\FinancesController"
    prefix:   api/v1
    type:     rest

staticlist:
    resource: "AppBundle\Controller\StaticListsController"
    prefix:   api/v1
    type:     rest

qualitas:
    resource: "AppBundle\Controller\QualitasController"
    prefix:   api/v1
    type:     rest

search:
    resource: "AppBundle\Controller\SearchesController"
    prefix:   api/v1
    type:     rest