NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

customers:
    resource: "AppBundle\Controller\CustomersController"
    prefix:   api/v1
    type:     rest

devices:
    resource: "AppBundle\Controller\DevicesController"
    prefix:   api/v1
    type:     rest

mapRoute:
    resource: "AppBundle\Controller\MapRouteController"
    prefix:   api/v1
    type:     rest

qualitas:
    resource: "AppBundle\Controller\QualitasController"
    prefix:   api/v1
    type:     rest