# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    fos_oauth_server.server:
        class: AppBundle\Services\FindnessOAuthServer
        arguments:
            - "@findness.oauth.storage"
            - "%fos_oauth_server.server.options%"

    findness.oauth.storage:
        class: AppBundle\Services\FindnessOAuthStorage
        arguments:
            - "@fos_oauth_server.client_manager"
            - "@fos_oauth_server.access_token_manager"
            - "@fos_oauth_server.refresh_token_manager"
            - "@fos_oauth_server.auth_code_manager"
            - "@fos_oauth_server.user_provider"
            - "@security.encoder_factory"
        public: false

    findness.rest.security.authentication.provider:
        class: AppBundle\Security\Authentication\Provider\RestProvider
        arguments:
            - ""
        public: false

    findness.rest.security.authentication.listener:
        class: AppBundle\Security\Firewall\RestListener
        arguments:
            - "@security.token_storage"
            - "@security.authentication.manager"
        public: false

    findness.push_notification.gcm:
        class: AppBundle\Services\GCM
        arguments: [%gcm_token%, %gcm_package_name%]

    findness.push_notification.apn:
        class: AppBundle\Services\APN
        arguments: [%apn_app_id%, %apn_pem_path%, %apn_sandbox%, %apn_pass_phrase%]

    findness.customer.registration:
        class: AppBundle\Services\CustomerRegistration
        arguments:
            "em": "@doctrine.orm.entity_manager"
            "mailer": "@mailer"
            "templateEngine": '@twig'

    findness.device.registration:
        class: AppBundle\Services\DeviceRegistration
        arguments:
            - "@doctrine.orm.entity_manager"

    findness.mapRoute.registration:
        class: AppBundle\Services\MapRouteRegistration
        arguments:
            - "@doctrine.orm.entity_manager"

    findness.transaction.registration:
        class: AppBundle\Services\TransactionRegistration
        arguments:
            - "%stripe_key%"
            - "%stripe_secret%"
            - "%paypal_client_id%"
            - "%paypal_secret%"
            - "@doctrine.orm.entity_manager"

    findness.qualitas:
        class: AppBundle\Services\QualitasSOAPApi
        arguments:
            - "%qualitas_username%"
            - "%qualitas_password%"
            - "%qualitas_geo_radio%"
            - "%findness_search_fee%"
            - "%findness_search_min%"
            - "%findness_search_extra_fee%"
            - "%findness_search_extra_fee_threshold%"
            - "%findness_search_iva_fee%"
            - "@besimple.soap.client.qualitasapi"
            - "@doctrine.orm.entity_manager"

    findness.company:
        class: AppBundle\Services\Company
        arguments:
            "em": "@doctrine.orm.entity_manager"

    findness.staticlist:
        class: AppBundle\Services\StaticList
        arguments:
            "em": "@doctrine.orm.entity_manager"
            "pushNotificationServices":
                "Android": "@findness.push_notification.gcm"
#                "IOS": "@findness.push_notification.apn"
            "mailer": "@mailer"
            "twig": "@twig"
            "logger": "@logger"

    findness.search:
        class: AppBundle\Services\Search
        arguments:
            "em": "@doctrine.orm.entity_manager"